# Generated by Django 4.1.5 on 2023-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1000, null=True)),
                ('lname', models.CharField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('phno', models.IntegerField(max_length=10, null=True)),
                ('servicedepartement', models.CharField(max_length=1000, null=True)),
                ('sevicesub', models.CharField(max_length=1000, null=True)),
                ('address', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
